### ISSUE TITLE
Auto Start Checking on the Test App

### ISSUE THREAD

**Issue by zebede22** [securevale/android-rasp#1]
It would be good if all tests would start automatically and would log results into logcat.
it would be useful automated systems where interaction is limited

**Comment by bmaciejm** [comment]
Hi, thank you for this proposal! 
What do you mean by `automatically`, without the need to create a builder and calling the `check` as described in this [section](https://github.com/securevale/android-rasp?tab=readme-ov-file#getting-started)?

How would you like to use this library on automated systems? Can you describe it in more detail?

**Comment by zebede22** [comment]
Sorry for the late answer,
Within the testing app we need to press the button to run tests (emulator, debugger)

In `automatically` I mean to run both checks when the app opens without clicking a button.

**Comment by bmaciejm** [comment]
Yup because this is the `sample app` whose purpose is just to show how the sample integration of the library should be.

If you want to achieve what you mentioned  just add the library itself as the dependency (check README how to do it) to some app you create for that purpose and then the shortest code snippet that will allow you to achieve what you want will be:

```
class SampleApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        SecureApp.init()
        
        SecureAppChecker.Builder(this, checkEmulator = true, checkDebugger = true)
            .build()
            .check()
    }
}
```
